### ISSUE TITLE
Jewellery box Castle Wars

### ISSUE THREAD

**Issue by SlipperyPickle** [PTYB/SlayerIssueTracker#182]
**Issue:** When using jewellery box to castle wars the script stops.
**Current behavior:** Script stops (I think it's because it tries to teleport to "Castle's wars arena" instead of "Castle Wars"
**Expected behavior:** Teleport to Castle Wars
**Screenshots/Video:** Not needed I think
**Master:**
**Task:**
**Logs:**
```12-20 21:03:20.762  2855  4923 I org.powbot.api.waiter.ActionWaiter:  [pool-47-thread-1] 12-20 21:03:20.762  INFO o.p.a.w.ActionWaiter - action waiter finished after 0
12-20 21:03:23.023  2855  4923 I com.pty.slayer.Slayer:  [pool-47-thread-1] 12-20 21:03:23.023  INFO c.p.s.Slayer - Tree Execution line: Init?[F] -> Knows task?[S] -> Has action?[F] -> Needs to bank?[S] -> Bank opened?[F] -> End last task?[F] -> In house?[S] -> Heal in house?[F] -> Heal in house?[F] -> Restore energy?[F] -> Restore special?[F] -> Restore prayer?[F] -> Teleporting from house
12-20 21:03:23.024  2855  4923 I com.pty.slayer.logic.inhouse.leafs.TeleportInHouse:  [pool-47-thread-1] 12-20 21:03:23.024  INFO c.p.s.l.i.l.TeleportInHouse - POH Location: Castle's wars arena | POH item Basic Jewellery Box
12-20 21:03:23.024  2855  4923 I com.pty.slayer.logic.inhouse.leafs.TeleportInHouse:  [pool-47-thread-1] 12-20 21:03:23.024  INFO c.p.s.l.i.l.TeleportInHouse - Teleporting with Jewellery Box to Castle's wars arena
12-20 21:03:23.024  2855  4923 E org.powbot.mobile.script.ScriptManager:  [pool-47-thread-1] 12-20 21:03:23.024 ERROR o.p.m.s.ScriptManager - script poll failed ([Private] PTY Slayer)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:  [pool-47-thread-1] 12-20 21:03:23.025 ERROR o.p.m.s.ScriptManager - java.util.NoSuchElementException: Array contains no element matching the predicate.
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at com.pty.slayer.logic.inhouse.leafs.TeleportInHouse.jewelleryBoxTeleport(TeleportInHouse.kt:207)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at com.pty.slayer.logic.inhouse.leafs.TeleportInHouse.execute(TeleportInHouse.kt:53)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.api.script.tree.TreeScript.poll(TreeScript.kt:19)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.mobile.script.ScriptManager$runScript$3.invokeSuspend(ScriptManager.kt:504)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:8)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:4)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:502)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:49)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at org.powbot.mobile.script.ScriptManager$start$3.invokeSuspend(ScriptManager.kt:232)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:        at java.lang.Thread.run(Thread.java:764)
12-20 21:03:23.025  2855  4923 E org.powbot.mobile.script.ScriptManager:
12-20 21:03:23.025  2855  4923 W System.err: java.util.NoSuchElementException: Array contains no element matching the predicate.
12-20 21:03:23.025  2855  4923 W System.err:    at com.pty.slayer.logic.inhouse.leafs.TeleportInHouse.jewelleryBoxTeleport(TeleportInHouse.kt:207)
12-20 21:03:23.025  2855  4923 W System.err:    at com.pty.slayer.logic.inhouse.leafs.TeleportInHouse.execute(TeleportInHouse.kt:53)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 I chatty  : uid=10061(com.jagex.oldscape.android) pool-47-thread- identical 10 lines
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.api.script.tree.TreeScript.poll(TreeScript.kt:19)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.mobile.script.ScriptManager$runScript$3.invokeSuspend(ScriptManager.kt:504)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:8)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:4)
12-20 21:03:23.025  2855  4923 W System.err:    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
12-20 21:03:23.025  2855  4923 W System.err:    at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
12-20 21:03:23.025  2855  4923 W System.err:    at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:502)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:49)
12-20 21:03:23.025  2855  4923 W System.err:    at org.powbot.mobile.script.ScriptManager$start$3.invokeSuspend(ScriptManager.kt:232)
12-20 21:03:23.025  2855  4923 W System.err:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-20 21:03:23.025  2855  4923 W System.err:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-20 21:03:23.025  2855  4923 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 21:03:23.025  2855  4923 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 21:03:23.025  2855  4923 W System.err:    at java.lang.Thread.run(Thread.java:764)
12-20 21:03:23.025  2855  4923 I FlagManager:  [pool-47-thread-1] 12-20 21:03:23.025  INFO FlagManager - Updating key current_script to value
12-20 21:03:23.027  2855  4923 I FlagManager:  [pool-47-thread-1] 12-20 21:03:23.027  INFO FlagManager - Updating key script_state to value Stopped```
**Additional information:**

**Comment by PTYB** [comment]
Will be fixed in next release, unfortunately you will need to do the following

- Change to another method of house teleport
- Save
- Change back
- Save

Will see if I can auto update it though.

**Comment by SlipperyPickle** [comment]
Works!
